name: Build

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    strategy:
      matrix:
        goos: [ 'linux' ]
        goarch: [ 'arm', 'arm64', 'amd64' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache-dependency-path: '**/go.sum'

      - name: Setup Protobuf prerequisites
        run: |
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Setup Go CTRF Json Reporter
        run: go install github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@latest

      - name: Download Borg
        run: |
          mkdir -p "$HOME/.local/bin"
          echo "PATH=$PATH:$HOME/.local/bin" >> "$GITHUB_ENV"
          
          curl -L -o "$HOME/.local/bin/borg" https://github.com/borgbackup/borg/releases/download/1.4.1/borg-linux-glibc228

      - name: Run tests
        run: make test-ci

      - name: Upload Test Results
        if: always()
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: ctrf-report.json

      - name: Build ${{ matrix.goos }}/${{ matrix.goarch }} binaries
        run: |
          case ${{ github.ref_name }} in
            v*)
              VERSION=${{ github.ref_name }}
              export VERSION=${VERSION#"v"}
              ;;
            *)
              export VERSION=snapshot-${{ github.sha }}
          esac
          
          if [[ ${{ matrix.goarch }} == "arm" ]]; then
            suffix_arch=armv7l
          else
            suffix_arch=${{ matrix.goarch }}
          fi
          
          export SUFFIX=${{ matrix.goos }}-${suffix_arch}
          
          make build-ci
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: '7'
          GOARM64: v8.0

      - name: Upload ${{ matrix.goos }}/${{ matrix.goarch }} artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_id }}_artifact_${{ matrix.goos }}-${{ matrix.goarch }}
          path: bin

  release:
    if: github.ref_type == 'tag'
    needs: [ 'build' ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Previous Tag
        id: previousTag
        run: |
          name=$(git --no-pager tag --sort=creatordate --merged ${{ github.ref_name }} | tail -2 | head -1)
          echo "previousTag: $name"
          echo "previousTag=$name" >> $GITHUB_ENV

      - name: Generate CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ env.previousTag }}
          writeToFile: false
          excludeTypes: build,chore,ci,docs,other,style,test

      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: ${{ github.run_id }}_artifacts
          delete-merged: true
          retention-days: 1

      - name: Retrieve artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.run_id }}_artifacts
          path: bin

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_PAT }}
          body: ${{ steps.changelog.outputs.changes }}
          files: bin/*
